### ISSUE TITLE
Cannot connect to the Remote Desktop

### ISSUE THREAD

**Issue by Shinoby1992** [danielguerra69/ubuntu-xrdp#1]
I can't connect to the Remote Desktop via vnc it doesn't matter which port i use
running it on localhost from a mac.
i have the same issue with all other docker images from you like the firefox docker image

btw: ssh does work

**Comment by danielguerra69** [comment]
This remote desktop uses RDP not VNC. Check Microsoft Remote Desktop in the mac App Store

**Comment by Shinoby1992** [comment]
oh god your image helped me i just tried out every every docker image online with a functioning sound in docker on a cloud vm. I just using your code and now all what i wanted to do work, i couldn't ecsactly use your configuration part for pulse audio because i get a error on using
`RUN dpkg-buildpackage -rfakeroot -uc -b`
because that seems not to work. 
But still the flash audio now does play without sound that is firstly enough :-)!! 
Thank you helped me a lot lot lot

**Comment by danielguerra69** [comment]
I know sound is hard.
With me it works. After
login pulseaudio should run.
I'm working on a kali version
and with this one I have to
start pulseaudio by hand and
then watch youtube with firefox.
Shal I close it now ?

(for this RUN dpkg-buildpackage -rfakeroot -uc -b check your pulseaudio version )

**Comment by Shinoby1992** [comment]
if its okay one question btw if you can help me it could be interested by others who want to maybe run multiple docker files and have a accessibility with vnc, if not i have to open a stackoverflow question.
i now have my custom made dockerfile with your config of using pulseaudio ect but using VNC so not RDP but still interesting problem... i want to run multiple container on a host. 
Now my problem is running 1 container is fine, i can access its via its port with "http://hostdns:5800"
but running multiple containers with a RDP or VNC i can just access the latest created, means if i use my docker compose file and scale it to 2 replicas
http://hostdns:5800 always redirects to the 2.nd created container.
is it somehow possible to automatically ports by scaling it up 5800, then the second container has 5801?
it seems that docker swarm does not support port ranges. and i could not handle it to create a macvlan i think thats the only way right?

**Comment by danielguerra69** [comment]
You have a port collision when two conatiners want to use the same port
docker run -p 5901:5900 -d somevnc
Left is the port on the docker-host (should be unique in the host.
Right is the port inside the container (so here the port the containers listens to)
The next vnc should run like docker run -p 5902:5900 -d somevnc
If you use docker run -p 5900 -d somevnc, docker will automaticly assign an outside
port. You can see the ports when you do a docker ps
