### ISSUE TITLE
not able to login

### ISSUE THREAD

**Issue by olvier** [danielguerra69/ubuntu-xrdp#13]
hi folks.

i am not able to login with the defaults ubuntu:ubuntu.

also changing the pw-hash doesnt help. (also with "escaping dollar sign with another dollar sign").
creating a new user with docker exec helps, but the user isnt a root user, so it doesnt help either.

any idea?

**Comment by fbartels** [comment]
Hi @olvier,

what is the exact value that you have in the compose file? I just spun up a test container based on the example compose file and am able to login with ubuntu as username and password.

**Comment by olvier** [comment]
hi felix,

i never worked with docker-compose. i always used portainer to build my containers.
till now i had no problems so far. i now changed the pw-hash in portainer to the hash from the yml (did not recognized it, sry) in the environment variables, but still not able to log-in.

**Comment by fbartels** [comment]
That hash is a build argument, not an environment variable. So if you just use portainer to pull the image from the docker hub it should just be ubuntu as the password. (The compose file is more for convenience, not a requirement).

Will later need to check if there is a problem with the pre-defined value in the dockerfile.

**Comment by olvier** [comment]
> That hash is a build argument, not an environment variable. So if you just use portainer to pull the image from the docker hub it should just be ubuntu as the password.

1. there was another pw-hash in the environments, way shorter than that one from die yml
2. ubuntu as pw didn't work
i just started to change some stuff, as untouched ubuntu didnt work

**Comment by fbartels** [comment]
Hmm.. indeed. If i don't set the hash in the compose file then i cannot login to a locally built image. I compared the hash from the default compose file with the default value in the dockerfile and they are different.

What also wonders me is that `openssl passwd -1 'newpassword'` prints out a different hash on each run, I would have expected this to be always be the same.

**Comment by danielguerra69** [comment]
For quick use danielguerra/ubuntu-xrdp:18.04. A change is comming up.

**Comment by danielguerra69** [comment]
The password hash is going to be in docker-entrypoint.sh. In docker-compose use environment: PASSWORDHASH or with docker run -e PASSWORDHASH= ...
