### ISSUE TITLE
Firefox and Chromium continually crash

### ISSUE THREAD

**Issue by mredig** [danielguerra69/ubuntu-xrdp#15]
I should first point out that this is less of an issue and more that it'd be a good thing to document:

As soon as I do anything real in Firefox (and I also did a chromium test a couple times) it crashes. If the load remains real light, it doesn't seem to be much of an issue (and throwing a larger vm at it seems to reduce the tendency, but with hugely diminishing returns).

Upon further investigation, I realized I had removed the --shm-size argument as I was initially running in a VM with 512 MB RAM and didn't know what would happen if the size was larger than was available. When trying this *as recommended* in a VM with ample RAM, everything runs smoothly. Noting how important that argument was in the README could have saved me probably 24 hours worth of troubleshooting. Also worth noting, in my LIMITED testing, I seem to have been able to set the shm as low as 256 and have things run smoothly.

FWIW, a workaround was to compile and install Midori, but it's not as complete of an experience as Firefox.

**Comment by danielguerra69** [comment]
What do you want me to do ? I have added a warning to the readme. Next time, rtfm...

**Comment by mredig** [comment]
Apologies - I didn't mean to upset you. My experience was simply that I was trying to adjust for my available circumstances and ran into some issues. I simply wanted to share my learnings to help people avoid this in the future. I greatly appreciate the work you've done and am very impressed with how smooth the experience was apart from my issue.

And yes, a note in the readme was all I wanted. Thank you. :)

**Comment by danielguerra69** [comment]
Oh I'm not upset. It always good to be clear. The readme is better now, thanks.
