### ISSUE TITLE
File sharing via clipboard not woroking

### ISSUE THREAD

**Issue by comio** [danielguerra69/ubuntu-xrdp#23]
Dear All,

First, thanks for this dockerfile. I don't
I think that we need to enable fuse support. Is it possible?

**Comment by danielguerra69** [comment]
For fuse and other complicated actions you need to run the container in privilleged mode with systemd as entrypoint. I could give it a try in the devel branch but i have had bad experience with systemd in docker

**Comment by danielguerra69** [comment]
You can share a file folder in your RDP-client in the current version

**Comment by comio** [comment]
Hi Daniel,

sharing folder is a good way. Why bad experience with systemd? Is dbus required to work?

Thanks a lot,

luigi

**Comment by danielguerra69** [comment]
Hi Luigi,

Systemd needs to run privileged. This means it can change all kinds of kernel settings and can be used to compromise you docker machine. So I don't prefer to use that. I am creating a systemd version for you so you can see how it works

**Comment by danielguerra69** [comment]
Hi Luigi,
There is a systemd branch you have to run it as follows:
docker run -d --name uxrdp --hostname terminalserver --shm-size 1g -p 3389:3389 --privileged danielguerra/ubuntu-xrdp:systemd
I have tested it drag & drop doesn't work on a mac. But copy paste of files works.

**Comment by comio** [comment]
Hi Daniel, Thanks a lot for your code. I had some tries buy I prefer to don't use systemd because it requires --privileged option.
thanks again.

luigi
