### ISSUE TITLE
use microphone in remote session

### ISSUE THREAD

**Issue by VladimirButorin** [danielguerra69/ubuntu-xrdp#24]
Hi Daniel,

I trying to use microphone on remote session but looks like it doesnt work. Microphone is enabled in RDP configuration on windows.

arecord -D default -r 16000 -f S16_LE -c 1 --period-size=512 --buffer-size=5120 -vv recorded_file.wav 

is unable to record some audio. Volume control shows that arecord using xrdp source, but it doesnt show any indication that capture is ongoing.

**Comment by danielguerra69** [comment]
Hi Vladimir,
I have tried it in a privileged systemd container but it dit not work.
I think the problem is in xrdp.
check
https://github.com/neutrinolabs/xrdp/issues/1179

**Comment by VladimirButorin** [comment]
Hi Daniel,
I found in neutrinolabs/xrdp documentation that audio capture is supported  only in NeutrinoRDP client. I built it on my Win10 with MSVC2017 but it produce no sound and absolute unstable.

https://github.com/neutrinolabs/xrdp/issues/849

**Comment by danielguerra69** [comment]
If read it well, it says, this feature is not working
