### ISSUE TITLE
remote desktop returning failure

### ISSUE THREAD

**Issue by kuczko** [danielguerra69/ubuntu-xrdp#31]
I have just started it on my pc and tried to connect to it from same PC via:

>$ rdesktop -g 1024x768 -u ubuntu -p ubuntu 172.17.0.2
>Connection established using SSL.
>ERROR: SSL_write: 1 (Success)
>$ echo $?
>76

This is what i see logged inside xrdp.log
>20191210-01:17:05] [INFO ] Socket 11: AF_INET6 connection received from ::ffff:172.17.0.1 port 58854
>[20191210-01:17:05] [DEBUG] Closed socket 11 (AF_INET6 ::ffff:172.17.0.2 port 3389)
>[20191210-01:17:05] [DEBUG] Closed socket 10 (AF_INET6 :: port 3389)
>[20191210-01:17:05] [DEBUG] TLSv1.3 enabled
>[20191210-01:17:05] [DEBUG] TLSv1.2 enabled
>[20191210-01:17:05] [DEBUG] Security layer: requested 3, selected 1
>[20191210-01:17:05] [DEBUG] Closed socket 11 (AF_INET6 ::ffff:172.17.0.2 port 3389)

How to connect inside?

**Comment by cmosguy** [comment]
@kuczko I am getting the same issue, did you ever resolve this on your side?

**Comment by kuczko** [comment]
Hi @cmosguy, nope - i dropped it as i spent to much time on it.

**Comment by cmosguy** [comment]
Hello to anyone going to this issue, do not waste your time with this repo.  @kuczko  and everyone should use this instead: https://github.com/RattyDAVE/docker-ubuntu-xrdp-mate-custom

**Comment by fbartels** [comment]
Based on the error message in the first post, your rdp client does reject the connection because of the self signed ssl certificate this image offer.

**Comment by rcarmo** [comment]
This image has no issues whatsoever, I just tested it and customised my own. New visitors should consider @cmosguy's commentary to be inaccurate (although the MATE image also looks nice).

**Comment by beechfuzz** [comment]
I also have no issues with this image, running it on an Ubuntu 19.04 headless host.

**Comment by martinpichlo** [comment]
trying to login via ms remote desktop (windows 10) fails for me, too. I got an error, that the authentification ist not active (in german: "Die Verbindung kann nicht fortgesetzt wreden, da die Authentifizierung nicht aktiv ist. Die Authentifizierung muss aktiviert sein, damit der Remotecomputer eine Verbindung herstellen kann"). 

PS: I've worked with an older version of this docker without any problems

**Comment by danielguerra69** [comment]
There seem to be many problems. First there is no certificate and key. The user ubuntu isn't there. I will fix it soon. For now you can use this image https://github.com/danielguerra69/alpine-xfce4-xrdp This is more recent work.

**Comment by danielguerra69** [comment]
Does it work now ?

**Comment by martinpichlo** [comment]
Yes, the alpine image works perfect. So I have no need for an ubuntu Version. 

PS: you suggest to set the ram to 1gb for the ubuntu image. I haven‘t found that suggestion for the apline image. What’s your opinion?

**Comment by danielguerra69** [comment]
I will change the readme, it needs 1G of shared memory for firefox
