### ISSUE TITLE
sshd not started by supervisord

### ISSUE THREAD

**Issue by mboehm21** [danielguerra69/ubuntu-xrdp#36]
Hi,

is there a reason why the supervisord is not configured to start sshd anymore? The file `/etc/supervisor/conf.d/sshd.conf` seems to be missing in the new version of the image. It would be no problem to mount it but according to documentation it should not be necessary.

Thanks.

**Comment by danielguerra69** [comment]
I made a mistake with git, it is fixed. The hub is building it.

**Comment by mboehm21** [comment]
Now everything is working again. Thanks again for maintaining this!
