### ISSUE TITLE
crudini missing

### ISSUE THREAD

**Issue by mboehm21** [danielguerra69/ubuntu-xrdp#37]
Hi,

sorry to open another issue but it seems that the crudini package is necessary for the entrypoint to work properly:

```
/usr/bin/docker-entrypoint.sh: line 65: crudini: command not found
/usr/bin/docker-entrypoint.sh: line 66: crudini: command not found
/usr/bin/docker-entrypoint.sh: line 67: crudini: command not found
```

It does not affect me but I still wanted to inform you. Thanks!

**Comment by danielguerra69** [comment]
I have added crudini to the packages installed.
Thanx for testing.
