### ISSUE TITLE
Ubuntu 20.04

### ISSUE THREAD

**Issue by baarkerlounger** [danielguerra69/ubuntu-xrdp#38]
Are there any plans to add a Ubuntu 20.04 based image now that it's the current LTS?

**Comment by danielguerra69** [comment]
I'm working on it, there are some troubles with it

**Comment by toastie89** [comment]
@danielguerra69 , is there anything you would need help with?

**Comment by danielguerra69** [comment]
I did start it but it didn't work. I can commit what I have done.

**Comment by danielguerra69** [comment]
There is a 20.04 branch, you can test it

**Comment by toastie89** [comment]
Thanks a lot for sharing and the good work. The image builds and runs fine on my end. I will continue testing next week.

**Comment by danielguerra69** [comment]
20.04 is working
