### ISSUE TITLE
Cert generation does not work

### ISSUE THREAD

**Issue by mboehm21** [danielguerra69/ubuntu-xrdp#40]
Hi,

I think line 54 in docker-entrypoint.sh should be something like that to work properly:

`openssl req -x509 -newkey rsa:2048 -nodes -keyout /etc/xrdp/key.pem -out /etc/xrdp/cert.pem -days 365 -subj "$CERTIFICATE_SUBJECT"`

I added the absolute paths and quoted the subject so that it can contain spaces.

Thanks.

**Comment by danielguerra69** [comment]
Crudini is missing. I am checking it now before I commit

**Comment by danielguerra69** [comment]
Your fix did the trick, and a default user_list thing.

**Comment by danielguerra69** [comment]
I tested it and all works. After this I did a commit. Does it solve you're problem now ?

**Comment by mboehm21** [comment]
All good, sorry for the late reply. Thanks for your great piece of container magic!
