### ISSUE TITLE
Installation of pepperflashplugin-nonfree blocks build process

### ISSUE THREAD

**Issue by sbaumgartner75** [danielguerra69/ubuntu-xrdp#44]
The installation of the pepperflashplugin-nonfree package tries to download the following files:

https://get.adobe.com/flashplayer/webservices/json/?platform_type=Linux&platform_arch=$arch&browser_dist=Chrome
https://fpdownload.adobe.com/pub/flashplayer/pdc/$upstream/flash_player_ppapi_linux.$arch.tar.gz

These files are no longer available - thus the installation fails.

Please remove the installation of this package as it blocks the build process.

**Comment by danielguerra69** [comment]
Confirmed
Setting up pepperflashplugin-nonfree (1.8.3+nmu1ubuntu1) ...
Build canceled.
There is an error in the script from pepperflash. I'm going to test flashplugin-installer instead

**Comment by danielguerra69** [comment]
I used this method, https://linoxide.com/linux-how-to/install-adobe-flash-player-linux-terminal/
Now local, it builds and works.

**Comment by sbaumgartner75** [comment]
Confirmed. Build succeeded.
