### ISSUE TITLE
any luck deploying this on openshift?

### ISSUE THREAD

**Issue by ckocyigit** [danielguerra69/ubuntu-xrdp#45]
Hey,

did anyone have any luck deploying this on openshift?

I mounted volumes and even the users.list as configmap/volume. 

I can connect via ssh on a route that points at the 22 port on the service.

But connecting via a route pointing to 3389 does not work. If I use the link via browser it downloads a binary file but Iam do not get any smarter analysing the file.

**Comment by danielguerra69** [comment]
Sorry no idea , good luck
