### ISSUE TITLE
Error: Copy Files from local machine to xrdp

### ISSUE THREAD

**Issue by zafhiel** [danielguerra69/ubuntu-xrdp#46]
Hi Guys!

in many installations of this wonderful docker image, I always get this error when I try to copy one file from the local machine to the xrdp.

![image](https://user-images.githubusercontent.com/13457923/111538997-61e2b600-873b-11eb-88f8-5c7432c24e47.png)

any ideas?

**Comment by danielguerra69** [comment]
This can only work if the container is running in privileged mode, also the the fuser modules must be loaded on the host docker machine.
I just made a docker container, the project which made it all possible can be found at https://github.com/neutrinolabs/xrdp

**Comment by zafhiel** [comment]
confirmed!

only need the `--privileged` flag
