### ISSUE TITLE
Ability to wget deb file and install it

### ISSUE THREAD

**Issue by MoonstarCoding** [danielguerra69/ubuntu-xrdp#48]
Is it possible to add something similar to what you have for `sudo` packages, but for `.deb` packages?

Something similar to:
```
for pkg in DPKG; do
    wget -O /tmp/Downloads/ "$pkg"
done

for pkg in `ls /tmp/Downloads/`; do
    dpkg -i "$pkg"
done
```

That way, we can have persistent installs of Discord and other things if the system accidentally reboots? Not an issue really, but would be nice. I am not that savvy with docker, so I couldn't really answer this myself.

**Comment by danielguerra69** [comment]
You can add your own services in /etc/supervisor/conf.d

**Comment by danielguerra69** [comment]
See the Readme
Installing additional packages during build

The Dockerfile has support for the build argument ADDITIONAL_PACKAGES to install additional packages during build. Either pass it with --build-arg during docker build or add it as args in your docker-compose.override.yml and run docker-compose build.
