### ISSUE TITLE
xrdp login failed for display 0 on custom build

### ISSUE THREAD

**Issue by MoonstarCoding** [danielguerra69/ubuntu-xrdp#49]
When I clone the GitHub and pass in my own apps to download, something must be going wrong because I lose all access to logging in to the container via RDP. It works just fine when I simply pull the image and run it, but when I build my own, I always encounter this error.

**Comment by danielguerra69** [comment]
What error ? logging  anything

**Comment by danielguerra69** [comment]
user ubuntu pass ubuntu

**Comment by MoonstarCoding** [comment]
@danielguerra69 It doesn't log anything. I log in, and I get a grey box with the error message "xrdp login failed for display 0". 
I found an image of the error: https://i.stack.imgur.com/jhQLP.png

**Comment by danielguerra69** [comment]
the logs are inside the container in /var/log/supervisor. Seems like a login error try . docker exec -ti  terminal-server adduser test
And then login with that user

**Comment by MoonstarCoding** [comment]
@danielguerra69 Docker will not launch the exec command. The command prompt instantly goes back to editing mode with no indication that it did anything, and logging in with the `test` user doesn't work.
That being said, I cloned the git and modified the Dockerfile to use a separate `RUN` instead of the existing one where the argument was placed. This worked and I can log in with the custom packages.

**Comment by MoonstarCoding** [comment]
I am closing this because my issue is technically solved, but not in the way that you would expect. This is one of those moments where the magic takes place in the Computer Science field and for some reason something compiles. 
Because it is separate from the existing docker image, I still can't get those logs either. If you have other ideas, I am all ears.

**Comment by danielguerra69** [comment]
The logs are inside you ubunt-xrdp container, docker exec -ti <containerid> bash  Then , cd /var/log/supervisor
