### ISSUE TITLE
openbox instead of xfce

### ISSUE THREAD

**Issue by DeAlexPesh** [danielguerra69/ubuntu-xrdp#51]
Hi. Can you help me replace xfce on openbox shell. I need lite shell with chrome in kiosk mode. It be work if I make:
`echo "openbox-session" > /etc/skel/.Xclients`

**Comment by danielguerra69** [comment]
git clone and then edit the docker file. Or make a Dockerfile like this :

FROM danielguerra/ubuntu-xrdp:latest
RUN echo "openbox-session" > /etc/skel/.Xclients

**Comment by DeAlexPesh** [comment]
Yes... I make this:
```
FROM danielguerra/ubuntu-xrdp:clean
RUN apt-get -y update \
 && apt-get -y purge firefox vlc adobe-flashplugin browser-plugin-.* xfce4.* \
 && apt-get -y autoremove \
 && apt-get -y autoclean \
 && apt-get -y install --no-install-recommends chromium-browser openbox \
 && rm -rf /var/cache/apt /var/lib/apt/lists \
 && echo "openbox-session" > /etc/skel/.Xclients
```
but have black screen with openbox menu. Help me please with chrome kiosk mode for all added user

**Comment by danielguerra69** [comment]
Normal for openbox to have a black screen, use youre right mouse button ...

**Comment by DeAlexPesh** [comment]
RMB show menu, but no open web-browser(

**Comment by danielguerra69** [comment]
Add youre own menu, check this ...
https://github.com/danielguerra69/soulseek/tree/master/openbox

**Comment by DeAlexPesh** [comment]
Can I make autostart chromium kiosk by start user session?
```
nano /etc/xdg/openbox/autostart
# Disable any form of screen saver
xset s off
# Disable screen blanking
xset s noblank
# Disable power management
xset -dpms
# Allow quitting the X server with CTRL-ATL-Backspace
setxkbmap -option terminate:ctrl_alt_bksp
setxkbmap -option startx:alt_x
# Start Chromium in kiosk mode
sed -i 's/"exited_cleanly":false/"exited_cleanly":true/' ~/.config/chromium/'Local State'
sed -i 's/"exited_cleanly":false/"exited_cleanly":true/; s/"exit_type":"[^"]\+"/"exit_type":"Normal"/' ~/.config/chromium/Default/Preferences
chromium-browser --disable-infobars --kiosk 'http://localhost:5000/'
```
does not give a result

**Comment by danielguerra69** [comment]
Bit off topic, but this is how to start chromium : chromium-browser --no-sandbox --disable-gpu

**Comment by DeAlexPesh** [comment]
I understand that. I do not understand where to register it for startup

**Comment by danielguerra69** [comment]
in .Xclients as I said before

**Comment by DeAlexPesh** [comment]
I make open chrome from menu, but /etc/xdg/openbox/autostart no work(
how make it work on start session?

**Comment by danielguerra69** [comment]
Read the openbox manual
