### ISSUE TITLE
Impossible to share audio with discord

### ISSUE THREAD

**Issue by JamesDAdams** [danielguerra69/ubuntu-xrdp#55]
Hi, 

first thanks for your dockerFile is very good and i use it everyday, i install chrome and discord and i have a probleme with discord.

Screen sharing works fine, except for sound I have this message : **Sound may not be available when sharing a screen on your device**

![Capture](https://user-images.githubusercontent.com/20860324/127549401-7cd7d561-02d6-4224-8059-1600c5719eea.PNG)

Do you have any idea where it might come from ?

Thanks

**Comment by danielguerra69** [comment]
This project work with pulseaudio. The source of discord needs to be compiled with pulseaudio.  
Does discord work at all , or is it the combination ?
https://www.reddit.com/r/discordapp/comments/f22vz6/guide_how_to_stream_audio_to_discord_on_linux/

**Comment by JamesDAdams** [comment]
yes it's work thanks :)
