### ISSUE TITLE
Retain applications & updates installed during runtime

### ISSUE THREAD

**Issue by gymnae** [danielguerra69/ubuntu-xrdp#7]
Hi, 
this image runs very well, thank you :)
Is there a way to retain applications installed over re-recreations of the container? Like installing a .deb or any package from the repo is gone when the container is re-created.
Cheers,

**Comment by danielguerra69** [comment]
You could use my dockerfile and add the packages you want and then rebuild it.
FROM danielguerra69/ubuntu-xrdp
RUN apt install mypackages

**Comment by gymnae** [comment]
That is a possibility, yes. Then I could also add a 
`RUN apt-get update && apt-get upgrade `
in the end.
Thanks.
